name: inner_spark_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.2.1
  isar: ^3.1.0+1
  json_annotation: ^4.8.1
  quiver: ^3.2.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.1.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  easy_localization: ^3.0.5
  easy_localization_loader: ^2.0.1
  freezed_annotation: ^2.4.1
  numberpicker: ^2.1.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/images/challenges/
    - assets/images/workouts/
    - assets/images/moods/


flutter_launcher_icons:
  image_path: assets/images/icon-512x512.png
  android: true
  ios: true
  adaptive_icon_background: "#B2E01E"
  adaptive_icon_foreground: assets/images/icon-foreground-512x512.png
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#B2E01E"


flutter_native_splash:
  color: "#FEFCF4"
  
  android_12:
    image: assets/images/icon-foreground-512x512.png
    icon_background_color: "#B2E01E"
    color: "#FEFCF4"
  